[package]
name = "circleci-test"
version = "0.1.0"
authors = ["lunasorcery <git@moonbase.lgbt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
