version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - run:
          name: Fetch python dependences
          command:  pip install -r requirements.txt
      - run:
          name: Fetch system dependencies
          command: sudo apt update && sudo apt install inkscape imagemagick
      - run:
          name: Inkscape help
          command: inkscape --version && inkscape --help
      - run:
          name: Build the site!
          command: ./build-site.py

workflows:
  version: 2
  build:
    jobs:
      - build
