version: 2.1
executors:
  exectr:
    docker:
      - image: dockerben/cpptemplate:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./../../vcpkg install fmt
      - run:
          name: Compile
          command: make all

workflows:
  version: 2
  build:
    jobs:
      - build
