version: 2.1
executors:
  exectr:
    docker:
      - image: dockerben/cpptemplate:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: install the build system # todo: put this in the docker image
          command: |
            apt-get update
            apt-get install -y python3-pip pkg-config ninja-build
            pip3 install meson
      - run:
          name: configure our milkshake
          command: meson setup build
      - run:
          name: compile the thing
          command: meson compile -C build

workflows:
  version: 2
  build:
    jobs:
      - build
