version: 2.1
executors:
  exectr:
    docker:
      - image: dockerben/cpptemplate:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install python3-pip
      - run: pip3 install meson
      - run: meson setup build
      - run: meson compile -C build

workflows:
  version: 2
  build:
    jobs:
      - build
